import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:3000/');
  await page.getByRole('button').filter({ hasText: /^$/ }).first().click();
  await page.getByRole('button', { name: 'Inicio de Sesión' }).click();
  await page.getByRole('textbox', { name: 'Usuario' }).click();
  await page.getByRole('textbox', { name: 'Usuario' }).fill('USER_ADMIN');
  await page.getByRole('textbox', { name: 'Contraseña' }).click();
  await page.getByRole('textbox', { name: 'Contraseña' }).fill('PASSWORD_ADMIN');
  await page.getByRole('button', { name: 'Iniciar Sesión' }).click();
  await page.getByRole('main').getByRole('button', { name: 'Editar' }).click();
  await page.getByRole('textbox', { name: 'Título de la sección' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Título de la sección' }).fill('test');
  await page.getByRole('textbox', { name: 'Escribe el título aquí' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Escribe el título aquí' }).fill('test');
  await page.getByRole('textbox', { name: 'Escribe el texto aquí' }).click();
  await page.getByRole('textbox', { name: 'Escribe el texto aquí' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Escribe el texto aquí' }).fill('test');
  await page.locator('div').filter({ hasText: /^Textotest$/ }).getByRole('button').nth(2).click();
  await page.getByRole('button', { name: 'Texto' }).click();
  await page.getByText('TextoNuevo texto. Escribe aqu').click();
  await page.locator('div').filter({ hasText: /^TextoNuevo texto\. Escribe aquí tu contenido\.$/ }).getByRole('button').first().click();
  await page.locator('div').filter({ hasText: /^TextoNuevo texto\. Escribe aquí tu contenido\.$/ }).getByRole('button').nth(1).click();
  await page.getByRole('button', { name: 'Título' }).click();
  await page.locator('div:nth-child(3) > .flex.items-center.justify-between > .inline-flex.items-center.justify-center.gap-2.whitespace-nowrap.text-sm.font-medium.ring-offset-background.transition-colors.focus-visible\\:outline-none.focus-visible\\:ring-2.focus-visible\\:ring-ring.focus-visible\\:ring-offset-2.disabled\\:pointer-events-none.disabled\\:opacity-50.\\[\\&_svg\\]\\:pointer-events-none.\\[\\&_svg\\]\\:size-4.\\[\\&_svg\\]\\:shrink-0.border.border-input.h-9.rounded-md.px-3.text-red-500').click();
  await page.locator('div').filter({ hasText: /^TextoNuevo texto\. Escribe aquí tu contenido\.$/ }).getByRole('button').nth(2).click();
  await page.getByRole('button', { name: 'Cancelar' }).click();
  await page.getByRole('main').getByRole('button', { name: 'Editar' }).click();
  await page.getByText('TextoLorem ipsum dolor sit').click();
  await page.locator('.inline-flex.items-center.justify-center.gap-2.whitespace-nowrap.text-sm.font-medium.ring-offset-background.transition-colors.focus-visible\\:outline-none.focus-visible\\:ring-2.focus-visible\\:ring-ring.focus-visible\\:ring-offset-2.disabled\\:pointer-events-none.disabled\\:opacity-50.\\[\\&_svg\\]\\:pointer-events-none.\\[\\&_svg\\]\\:size-4.\\[\\&_svg\\]\\:shrink-0.border.border-input.h-9.rounded-md.px-3.text-red-500').first().click();
  await page.getByRole('main').getByRole('button').filter({ hasText: /^$/ }).nth(2).click();
  await page.getByRole('button', { name: 'Guardar' }).click();
  await page.getByRole('main').getByRole('button', { name: 'Editar' }).click();
  await page.getByRole('button', { name: 'Imagen' }).click();
  await page.getByRole('textbox', { name: 'URL de la imagen' }).click();
  await page.getByRole('img', { name: 'Nueva imagen' }).click();
  await page.locator('div').filter({ hasText: /^ImagenURL de la imagenTexto alternativoVista previa:$/ }).getByRole('button').nth(2).click();
  await page.getByRole('button', { name: 'Slider' }).click();
  await page.locator('div').filter({ hasText: /^Imagen 1URL de la imagen:$/ }).getByPlaceholder('https://ejemplo.com/imagen.jpg').click();
  await page.locator('div').filter({ hasText: /^Imagen 2URL de la imagen:$/ }).getByPlaceholder('https://ejemplo.com/imagen.jpg').click();
  await page.locator('div').filter({ hasText: /^Imagen 2$/ }).getByRole('button').click();
  await page.getByRole('button', { name: 'Agregar Imagen' }).click();
  await page.getByRole('button', { name: 'Guardar' }).click();
  await page.getByRole('main').getByRole('button').filter({ hasText: /^$/ }).nth(1).click();
  await page.getByRole('main').getByRole('button').filter({ hasText: /^$/ }).first().click();
  await page.getByRole('button', { name: 'Eliminar' }).click();
  await page.getByText('No hay secciones de contenidoCrear Primera Sección').click();
  await page.getByRole('button').filter({ hasText: /^$/ }).nth(1).click();
});