import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:3000/');
  await page.getByRole('button').filter({ hasText: /^$/ }).first().click();
  await page.getByRole('button', { name: 'Inicio de Sesión' }).click();
  await page.getByRole('textbox', { name: 'Usuario' }).click();
  await page.getByRole('textbox', { name: 'Usuario' }).fill('admin');
  await page.getByRole('textbox', { name: 'Contraseña' }).click();
  await page.getByRole('textbox', { name: 'Contraseña' }).fill('123');
  await page.getByRole('button', { name: 'Iniciar Sesión' }).click();
  await page.getByRole('button').filter({ hasText: /^$/ }).first().click();
  await page.getByRole('button', { name: 'Productos' }).click();
  await page.getByRole('button', { name: 'Nuevo Producto' }).click();
  await page.getByRole('textbox', { name: 'Nombre del producto' }).fill('testt');
  await page.getByRole('textbox', { name: 'Descripción' }).click();
  await page.getByRole('textbox', { name: 'Descripción' }).fill('test');
  await page.getByRole('spinbutton', { name: 'Precio' }).click();
  await page.getByRole('spinbutton', { name: 'Precio' }).fill('1212');
  await page.getByRole('textbox', { name: 'Link de MercadoLibre' }).click();
  await page.getByRole('textbox', { name: 'Link de MercadoLibre' }).click();
  await page.getByRole('textbox', { name: 'Link de MercadoLibre' }).fill('https://articulo.mercadolibre.com.ar/MLA-1510490703-bicicleta-dencar-paseo-2001-infantil-rodado-22-7vel-fiat-_JM#polycard_client=recommendations_home_navigation-recommendations&reco_backend=machinalis-homes-univb-equivalent-offer&reco_client=home_navigation-recommendations&reco_item_pos=0&reco_backend_type=function&reco_id=936f08b0-9214-40ca-99ca-1cfb07948a24&c_id=/home/navigation-recommendations/element&c_uid=89bd6ed4-b8d7-4638-a59e-6c9e59c88c3b');
  await page.locator('div').filter({ hasText: /^URL de la imagen del producto$/ }).click();
  await page.getByRole('textbox', { name: 'https://ejemplo.com/imagen.jpg' }).fill('https://http2.mlstatic.com/D_NQ_NP_631221-MLA89547102213_082025-O.webp');
  await page.getByRole('button', { name: 'Agregar Producto' }).click();
  const page1Promise = page.waitForEvent('popup');
  await page.getByRole('button', { name: 'Ver en ML' }).click();
  const page1 = await page1Promise;
  await page.getByRole('main').getByRole('button', { name: 'Editar' }).click();
  await page.getByRole('dialog', { name: 'Editar Producto' }).click();
  await page.getByRole('button', { name: 'Close' }).click();
  await page.locator('div').filter({ hasText: 'testttest1212Ver en MLEditar' }).nth(2).click();
  await page.getByRole('textbox', { name: 'Buscar productos...' }).click();
  await page.getByRole('textbox', { name: 'Buscar productos...' }).fill('test');
  await page.getByText('testttest1212Ver en MLEditar').click();
  await page.getByRole('main').getByRole('button').filter({ hasText: /^$/ }).click();
  await page.getByRole('button').filter({ hasText: /^$/ }).nth(1).click();
  await page.getByRole('link', { name: 'Club del 1500 Oficial' }).click();
});